news_portal/news/urls.py
from django.urls import path
# Импортируем созданное нами представление
from .views import (
   NewsList, NewsDetail, NewsSearch,
   PostCreate, PostUpdate, PostDelete, CategoryNewsList, Subscribe, BeAuthor)


urlpatterns = [
   # path — означает путь.
   # В данном случае путь ко всем товарам у нас останется пустым,
   # чуть позже станет ясно почему.
   # Т.к. наше объявленное представление является классом,
   # а Django ожидает функцию, нам надо представить этот класс в виде view.
   # Для этого вызываем метод as_view.
   path('', NewsList.as_view(), name='news_list'),
   path('<int:pk>', NewsDetail.as_view(), name='news_detail'),
   path('search/', NewsSearch.as_view()),
   path('create/', PostCreate.as_view(), name='news_create'),
   path('<int:pk>/update/', PostUpdate.as_view(), name='news_create'),
   path('<int:pk>/delete/', PostDelete.as_view(), name='news_delete'),
   path('categories/<int:pk>', CategoryNewsList.as_view(), name='news_category'),
   path('categories/<int:pk>/subscribe/', Subscribe.as_view(), name='news_subscribe'),
   path('new_author/', BeAuthor.as_view(), name='new_author'),
]

news_portal/news_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('', RedirectView.as_view(url='/news/')),
    path("accounts/", include("allauth.urls")),
]

news_portal/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Author(models.Model):
    auth_user = models.OneToOneField(User, on_delete=models.CASCADE)
    auth_rating = models.IntegerField(default=0)

    def update_rating(self):
        post_rating_q = self.post_set.aggregate(post_r=models.Sum('rating'))
        post_rating = 0
        post_rating += post_rating_q.get('post_r')

        comm_rating_q = self.auth_user.comment_set.aggregate(comm_r=models.Sum('rating'))
        comm_rating = 0
        comm_rating += comm_rating_q.get('comm_r')

        comm_auth_rating_q = Comment.objects.filter(post__author=self).aggregate(comm_auth_r=models.Sum('rating'))
        comm_auth_rating = 0
        comm_auth_rating += comm_auth_rating_q.get('comm_auth_r')

        self.auth_rating = post_rating*3+comm_rating+comm_auth_rating
        self.save()

    def __str__(self):
        return f'Author: {self.auth_user.username}'


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return str(self.name)


class Post(models.Model):

    article = 'AR'
    news = 'NW'

    POSITIONS = [
        (article, 'Статья'),
        (news, 'Новость'),
    ]
    author = models.ForeignKey('Author', on_delete=models.CASCADE)
    post_type = models.CharField(
        max_length=2, choices=POSITIONS, default=news)
    time_create = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(
        'Category', through='Postcategory')
    head = models.CharField(max_length=128)
    text = models.TextField(default='')
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        if len(self.text) > 124:
            return f"{self.text[:125]}..."
        return f"{self.text}"

    def __str__(self):
        return f'{self.post_type} {self.head}'

    def get_absolute_url(self):
        return reverse('news_detail', args=[str(self.id)])


class PostCategory(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.post.head} - {self.category.name}'


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    time_create = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'{self.text[:20]}...'

news_portal/news/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = [
            #    'author',
               'post_type',
               'category',
               'head',
               'text',
            ]

    # def clean(self):
    #     cleaned_data = super().clean()
    #     description = cleaned_data.get("description")
    #     if description is not None and len(description) < 20:
    #         raise ValidationError({
    #             "description": "Описание не может быть менее 20 символов."
    #         })

    #     name = cleaned_data.get("name")
    #     if name == description:
    #         raise ValidationError(
    #             "Описание не должно быть идентично названию."
    #         )

    #     return cleaned_data

news_portal/news/views.py
import logging

from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy

# Create your views here.
from django.views.generic import (
            ListView, DetailView,
            CreateView, UpdateView, DeleteView, View)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.cache import cache

from .models import Category, Post, Author
from .filters import PostFilter
from .forms import PostForm

logger = logging.getLogger(__name__)
print('name of app', __name__)

class NewsSearch(ListView):
    model = Post
    ordering = '-time_create'
    # Указываем имя шаблона, в котором будут все инструкции о том,
    # как именно пользователю должны быть показаны наши объекты
    template_name = 'search.html'
    # Это имя списка, в котором будут лежать все объекты.
    # Его надо указать, чтобы обратиться к списку объектов в html-шаблоне.
    context_object_name = 'news'
    # Отфильтровываем из статей и новостей только новости
    paginate_by = 10

    def get_queryset(self):
        logger.info("Info from view listview ")
        # Получаем обычный запрос
        queryset = super().get_queryset()
        # Используем наш класс фильтрации.
        # self.request.GET содержит объект QueryDict, который мы рассматривали
        # в этом юните ранее.
        # Сохраняем нашу фильтрацию в объекте класса,
        # чтобы потом добавить в контекст и использовать в шаблоне.
        self.filterset = PostFilter(self.request.GET, queryset)
        # Возвращаем из функции отфильтрованный список товаров
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        # С помощью super() мы обращаемся к родительским классам
        # и вызываем у них метод get_context_data с теми же аргументами,
        # что и были переданы нам.
        # В ответе мы должны получить словарь.
        context = super().get_context_data(**kwargs)
        # К словарю добавим текущую дату в ключ 'time_now'.
        context['filterset'] = self.filterset
        return context


class NewsList(ListView):
    model = Post
    ordering = '-time_create'
    # Указываем имя шаблона, в котором будут все инструкции о том,
    # как именно пользователю должны быть показаны наши объекты
    template_name = 'news.html'
    # Это имя списка, в котором будут лежать все объекты.
    # Его надо указать, чтобы обратиться к списку объектов в html-шаблоне.
    context_object_name = 'news'
    # Отфильтровываем из статей и новостей только новости
    paginate_by = 10

    # def get_queryset(self):
    #     return super().get_queryset().filter(post_type=Post.news)

    def get_context_data(self, **kwargs):
        # test logger
        logger.warning("Warning from view listview ")
        # С помощью super() мы обращаемся к родительским классам
        # и вызываем у них метод get_context_data с теми же аргументами,
        # что и были переданы нам.
        # В ответе мы должны получить словарь.
        context = super().get_context_data(**kwargs)
        # К словарю добавим текущую дату в ключ 'time_now'.
        # context['time_now'] = datetime.utcnow()
        # Добавим ещё одну пустую переменную,
        # чтобы на её примере рассмотреть работу ещё одного фильтра.
        # context['next_sale'] = None
        user = self.request.user
        context['author_user'] = False
        if not user.is_anonymous and Author.objects.filter(auth_user=user).exists():
            context['author_user'] = True
        context['next_sale'] = "Распродажа в среду!"
        return context


class NewsDetail(DetailView):
    # model = Post
    template_name = 'neww.html'
    context_object_name = 'neww'
    queryset = Post.objects.all()

    # переопределяем метод получения объекта, как ни странно
    def get_object(self, *args, **kwargs):
        # кэш очень похож на словарь, и метод get действует так же.
        # Он забирает значение по ключу, если его нет, то забирает None.
        obj = cache.get(f'post-{self.kwargs["pk"]}', None)
        # если объекта нет в кэше, то получаем его и записываем в кэш
        if not obj:
            obj = super().get_object(queryset=self.queryset)
            cache.set(f'post-{self.kwargs["pk"]}', obj)
        return obj


class PostCreate(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    # Указываем нашу разработанную форму
    form_class = PostForm
    permission_required = ('news.add_post',)
    # модель товаров
    model = Post
    # и новый шаблон, в котором используется форма.
    template_name = 'post_edit.html'
    # raise_exception = True

    def form_valid(self, form):
        form.instance.author = Author.objects.get(auth_user=self.request.user)
        return super().form_valid(form)


class PostUpdate(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    form_class = PostForm
    permission_required = ('news.change_post',)
    model = Post
    template_name = 'post_edit.html'


class PostDelete(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    permission_required = ('news.delete_post',)
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('news_list')


class CategoryNewsList(ListView):
    model = Post
    template_name = 'news_category.html'
    context_object_name = 'news_category'

    def get_queryset(self):
        self.category = get_object_or_404(Category, id=self.kwargs['pk'])
        return (super().get_queryset().
                filter(category=self.category).
                order_by('-time_create'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_subscriber'] = self.request.user not in self.category.subscribers.all()
        context['category'] = self.category
        return context


class Subscribe(LoginRequiredMixin, View):
    def get(self, request, pk):
        user = request.user
        category = Category.objects.get(id=pk)
        category.subscribers.add(user)
        message = 'Вы успешно подписались на категорию'
        return render(request, 'news_subscribe.html', {'category': category,
                                                       'message': message})


class BeAuthor(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        new_author = Author.objects.create(auth_user=user)
        message = 'Вы успешно стали автором'
        return render(request, 'new_author.html', {'message': message})

news_portal/templates/new_author.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% block title %}
        Автор
{% endblock title %}

{% load custom_filters %}

{% block content %}
<h1>{{message}}</h1>



<!-- {% if perms.news.delete_post %}
<a href="{{ neww.id }}/delete/" class="btn btn-danger">Delete</a>
{% endif %}
{% if perms.news.change_post %}
<a href="{{ neww.id }}/update/" class="btn btn-primary">Update</a>
{% endif %}
{% endblock content %} -->

news_portal/templates/news.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% block title %}
Новости
{% endblock title %}

{% load custom_filters %}

<!-- Подключаем новый файл с нашим тегом -->
{% load custom_tags %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Все посты</h1>
   <!-- Используем переданную из представления переменную time_now
   и применяем к ней фильтр date. По назначению этот фильтр очень похож
   на метод strftime у объекта datetime в Python — вывод времени
   в указанном формате. -->
   <!-- <h3>Добавленное поле</h3>
   <h3>{{ time_now|date:'d M Y' }}</h3>
   <h3>Добавленный тег</h3>
   <h3>{% current_time '%b %d %Y' %}</h3> -->
    <!-- Если в переменной next_sale будет None,
   то выведется указанный в фильтре текст -->

   <hr>
<!-- Выводим новости, только если они есть с помощью тега if -->
{% if news %}
<table class="table">
    <tr>
        <!-- <th>ID</th> -->
        <th>Тип</th>
        <th>Заголовок</th>
        <th>Дата публикации</th>
        <th>Текст</th>
        <th>Категории</th>

    </tr>


    {% for neww in news %}
    <tr>
        <!-- <td><a href="/news/{{neww.id}}"> {{neww.id }}</a></td> -->
        <td>{{ neww.get_post_type_display}}</td>
        <td><a href="{% url 'news_detail' neww.id %}">{{ neww.head | censor | censor:"Sword"}}</a></td>
        <td>{{ neww.time_create | date:'d M Y'}}</td>
        <td>{{ neww.text|truncatechars:20 }}</td>
        <td>{% for category in neww.category.all %}
            <a href="{% url 'news_category' category.id %}" class="btn btn-info"> {{category}} </a>
        {% endfor %}
        </td>
    </tr>
    {% endfor %}

</table>

{# Добавляем пагинацию на страницу #}

{# Информация о предыдущих страницах #}
{% if page_obj.has_previous %}
    <a href="?page=1">1</a>
    {% if page_obj.previous_page_number != 1 %}
        ...
        <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }}

{# Информация о следующих страницах #}
{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
    {% if paginator.num_pages != page_obj.next_page_number %}
        ...
        <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
    {% endif %}
{% endif %}

{% else %}
    <!-- Если новостей нет, говорим, что новостей нет ;) -->
    <h2>Новостей нет!</h2>
{% endif %}
<p></p>
<div>
{% if perms.news.add_post %}
    {% if author_user %}
        <a href="{% url 'news_create' %}" class="btn btn-primary">Написать новость</a>
    {% endif %}
    {% if not author_user %}
        <a href="{% url 'new_author' %}" class="btn btn-primary">Стать автором</a>
    {% endif %}
{% endif %}
</div>
{% endblock content %}

news_portal/templates/news_category.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% block title %}
Новости категории
{% endblock title %}

{% load custom_filters %}

<!-- Подключаем новый файл с нашим тегом -->
{% load custom_tags %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Все посты категории {{category}}</h1>
   <!-- Используем переданную из представления переменную time_now
   и применяем к ней фильтр date. По назначению этот фильтр очень похож
   на метод strftime у объекта datetime в Python — вывод времени
   в указанном формате. -->
   <!-- <h3>Добавленное поле</h3>
   <h3>{{ time_now|date:'d M Y' }}</h3>
   <h3>Добавленный тег</h3>
   <h3>{% current_time '%b %d %Y' %}</h3> -->
    <!-- Если в переменной next_sale будет None,
   то выведется указанный в фильтре текст -->

   <hr>
<!-- Выводим новости, только если они есть с помощью тега if -->
{% if news_category %}
{% if is_not_subscriber %}
        <p class="text-center"><a href="{% url 'news_subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться на категорию</a></p>
{% endif %}
<table class="table">
    <tr>
        <!-- <th>ID</th> -->
        <th>Тип</th>
        <th>Заголовок</th>
        <th>Дата публикации</th>
        <th>Текст</th>
        <th>Категории</th>
    </tr>


    {% for neww in news_category %}
    <tr>
        <!-- <td><a href="/news/{{neww.id}}"> {{neww.id }}</a></td> -->
        <td>{{ neww.get_post_type_display}}</td>
        <td><a href="{% url 'news_detail' neww.id %}">{{ neww.head | censor | censor:"Sword"}}</a></td>
        <td>{{ neww.time_create | date:'d M Y'}}</td>
        <td>{{ neww.text|truncatechars:20 }}</td>
        <td>{% for category in neww.category.all %}
            <a href="{% url 'news_category' category.id %}" class="btn btn-info"> {{category}} </a>
        {% endfor %}
        </td>

    </tr>
    {% endfor %}

</table>

{# Добавляем пагинацию на страницу #}

{# Информация о предыдущих страницах #}
{% if page_obj.has_previous %}
    <a href="?page=1">1</a>
    {% if page_obj.previous_page_number != 1 %}
        ...
        <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }}

{# Информация о следующих страницах #}
{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
    {% if paginator.num_pages != page_obj.next_page_number %}
        ...
        <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
    {% endif %}
{% endif %}

{% else %}
    <!-- Если новостей нет, говорим, что новостей нет ;) -->
    <h2>Новостей нет!</h2>
{% endif %}
<p></p>
<div>
{% if perms.news.add_post %}
<a href="{% url 'news_create' %}" class="btn btn-primary">Create news</a>
{% endif %}
</div>
{% endblock content %}

news_portal/templates/news_notify.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<h1> Здравствуйте! В категории, на которую вы подписаны, была создана <a href="{{link}}">новость</a></h>
<p>{{head}}</p>
<p>{{text}}</p>
</body>
</html>

news_portal/templates/news_notify_daily.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<h1> Здравствуйте! В категории, на которую вы подписаны,
     за неделю были добавлены следующие статьи <a href="{{link}}">новость</a></h>
<p>{{head}}</p>
<p>{{text}}</p>
<ul>
    {% for post in posts %}
    <li><a href="{{ link }}{{ post.get_absolute_url }}">{{post.head}}</a> </li>
    {% endfor %}

</ul>
</body>
</html>

news_portal/templates/news_notify_weekly.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<h1> Здравствуйте! В категории, на которую вы подписаны,
     за неделю были добавлены следующие статьи </h>

<ul>
    {% for post in posts %}
    <li><a href="{{ link }}{{ post.get_absolute_url }}">{{post.head}}</a> </li>
    {% endfor %}

</ul>
</body>
</html>

news_portal/templates/news_subscribe.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% block title %}
        Подписка
{% endblock title %}

{% load custom_filters %}

{% block content %}
<h1>{{message}}</h1>



<!-- {% if perms.news.delete_post %}
<a href="{{ neww.id }}/delete/" class="btn btn-danger">Delete</a>
{% endif %}
{% if perms.news.change_post %}
<a href="{{ neww.id }}/update/" class="btn btn-primary">Update</a>
{% endif %}
{% endblock content %} -->

news_portal/templates/neww.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% block title %}
Новость
{% endblock title %}

{% load custom_filters %}

{% block content %}
<h1>Новость</h1>
<dl class="row">
    <dt class="col-sm-3">Автор:</dt>
    <dd class="col-sm-9">{{ neww.author.auth_user.username }}</dd>
    <dt class="col-sm-3">Дата создания:</dt>
    <dd class="col-sm-9">{{ neww.time_create | date:'d M Y' }}</dd>
    <dt class="col-sm-3">Тип:</dt>
    <dd class="col-sm-9">{{ neww.get_post_type_display }}</dd>
    <dt class="col-sm-3">Заголовок:</dt>
    <dd class="col-sm-9">{{ neww.head | censor | censor:"Санитарным" | censor:"Sword"}}</dd>
    <dt class="col-sm-3">Содержание:</dt>
    <dd class="col-sm-9">{{ neww.text | censor | censor:"Санитарным" | censor:"lorem"}}</dd>
    <dt class="col-sm-3">Категории:</dt>
    <dd class="col-sm-9">
        {% for cat in neww.category.all %}
        {{cat.name}},
        {% endfor %}</dd>
</dl>
{% if perms.news.delete_post %}
<a href="{{ neww.id }}/delete/" class="btn btn-danger">Delete</a>
{% endif %}
{% if perms.news.change_post %}
<a href="{{ neww.id }}/update/" class="btn btn-primary">Update</a>
{% endif %}
{% endblock content %}

news_portal/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление Новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.head }}"?</p>
    <input type="submit" value="Delete" class="btn btn-primary" />
</form>
{% endblock content %}

news_portal/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новость / Статья</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" class="btn btn-primary" />
</form>
{% endblock content %}

news_portal/templates/product.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

<!-- Название у нас будет Product -->
{% block title %}
Product
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ product }}</h1>
{% endblock content %}

news_portal/templates/search.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% block title %}
Поиск постов
{% endblock title %}

{% load custom_filters %}

<!-- Подключаем новый файл с нашим тегом -->
{% load custom_tags %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Поиск постов</h1>
   <!-- Используем переданную из представления переменную time_now
   и применяем к ней фильтр date. По назначению этот фильтр очень похож
   на метод strftime у объекта datetime в Python — вывод времени
   в указанном формате. -->
   <!-- <h3>Добавленное поле</h3>
   <h3>{{ time_now|date:'d M Y' }}</h3>
   <h3>Добавленный тег</h3>
   <h3>{% current_time '%b %d %Y' %}</h3> -->
    <!-- Если в переменной next_sale будет None,
   то выведется указанный в фильтре текст -->

   <hr>

   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" class="btn btn-primary" />
   </form>
<!-- Выводим новости, только если они есть с помощью тега if -->
{% if news %}
<table class="table">
    <tr>
        <th>ID</th>
        <th>Тип</th>
        <th>Заголовок</th>
        <th>Дата публикации</th>
        <th>Текст</th>
    </tr>


    {% for neww in news %}
    <tr>
        <td><a href="/news/{{neww.id}}"> {{neww.id }}</a></td>
        <td>{{ neww.get_post_type_display}}</td>
        <td>{{ neww.head | censor | censor:"Sword"}}</td>
        <td>{{ neww.time_create | date:'d M Y'}}</td>
        <td>{{ neww.text|truncatechars:20 }}</td>
    </tr>
    {% endfor %}

</table>

{# Добавляем пагинацию на страницу #}

{# Информация о предыдущих страницах #}
{% if page_obj.has_previous %}
    <a href="?{% url_replace page=1 %}">1</a>
    {% if page_obj.previous_page_number != 1 %}
        ...
        <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }}

{# Информация о следующих страницах #}
{% if page_obj.has_next %}
    <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
    {% if paginator.num_pages != page_obj.next_page_number %}
        ...
        <a href="?{ url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
    {% endif %}
{% endif %}

{% else %}
    <!-- Если новостей нет, говорим, что новостей нет ;) -->
    <h2>Новостей нет!</h2>
{% endif %}


{% endblock content %}