proj_D32/proj_D32/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path('products/', include('simpleapp.urls')),
    path('appointments/', include('appointment.urls')),

]

proj_D32/simpleapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
from django.core.validators import MinValueValidator


# Товар для нашей витрины
class Product(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True, # названия товаров не должны повторяться
    )
    description = models.TextField()
    quantity = models.IntegerField(
        validators=[MinValueValidator(0)],
    )
    # поле категории будет ссылаться на модель категории
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='products', # все продукты в категории будут доступны через поле products
    )
    price = models.FloatField(
        validators=[MinValueValidator(0.0)],
    )

    def __str__(self):
        return f'{self.name.title()}: {self.description[:20]}'

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])


# Категория, к которой будет привязываться товар
class Category(models.Model):
    # названия категорий тоже не должны повторяться
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name.title()

proj_D32/templates/make_appointment.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Уведомление</h1>
<hr>
<form action="{% url 'make_appointment' %}" method="post">
    {% csrf_token %}
    <label for="client_name">Имя клиента</label>
    <input type="text" name="client_name"></input>
    <label for="message">Сообщение</label>
    <input type="text" name="message"></input>
    <label for="date">Дата</label>
    <input type="date" name="date"></input>

    <input type="submit" class="btn "/>
</form>
{% endblock content %}

proj_D32/templates/product_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

proj_D32/templates/product_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

proj_D32/templates/products.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

<!-- Название у нас будет products -->
{% block title %}
Products
{% endblock title %}

{% load custom_filters %}

<!-- Подключаем новый файл с нашим тегом -->
{% load custom_tags %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Все товары</h1>
   <!-- Используем переданную из представления переменную time_now
   и применяем к ней фильтр date. По назначению этот фильтр очень похож
   на метод strftime у объекта datetime в Python — вывод времени
   в указанном формате. -->
   <h3>Добавленное поле</h3>
   <h3>{{ time_now|date:'d M Y' }}</h3>
   <h3>Добавленный тег</h3>
   <h3>{% current_time '%b %d %Y' %}</h3>
    <!-- Если в переменной next_sale будет None,
   то выведется указанный в фильтре текст -->
   <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о распродаже!" }} </h3>

   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>
   <hr>
<!-- Выводим товары, только если они есть с помощью тега if -->
{% if products %}
<table>
    <tr>
        <td>Название</td>
        <td>Описание</td>
        <td>Категория</td>
        <td>Цена</td>
        <td>Количество</td>
        {# Условие получается составным. #}
        {% if perms.simpleapp.change_product or perms.simpleapp.delete_product %}
        <td>Действия</td>
        {% endif %}
    </tr>

    <!-- Для каждого товара будете генерироваться новая строчка,

    т.е. новый HTML код, который указан в теле цикла.
    При этом сам цикл работает точно так же, как и в Python.
    product — переменная цикла, т.е. наш товар полученный из списка -->
    {% for product in products %}
    <tr>
        <!-- Не забываем, что переменные в шаблоне ничем не отличаются

         от переменных в Python. Здесь также можно получать доступ к
         полям объекта модели. Например, здесь мы выводим имя,
         в следующем столбце описание, и т.д.  -->
        <td>{{ product.name }}</td>
        <td>{{ product.description|truncatewords:2 }}</td>
        <td>{{ product.category.name }}</td>
        <td>{{ product.price|currency:"usd" }}</td>
        <td>{{ product.quantity }}</td>
        <td>
            {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
            {% if perms.simpleapp.change_product %}
            <a href="{% url 'product_update' pk=product.id %}">Изменить</a>
            {% endif %}
            {% if perms.simpleapp.delete_product %}
            <a href="{% url 'product_delete' product.id %}">Удалить</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}

</table> <!-- ... и таблицы -->
{% else %}
    <!-- Если товаров нет, говорим, что товаров нет ;) -->
    <h2>Товаров нет!</h2>
{% endif %}

{# Добавляем пагинацию на страницу #}

{# Информация о предыдущих страницах #}
{% if page_obj.has_previous %}
    <a href="?page=1">1</a>
    {% if page_obj.previous_page_number != 1 %}
        ...
        <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }}

{# Информация о следующих страницах #}
{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
    {% if paginator.num_pages != page_obj.next_page_number %}
        ...
        <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
    {% endif %}
{% endif %}

{% endblock content %}